# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24f20ca20bfe5428c96d4436cb93e7255a9f9ebe9f0021eff257ab10e7e244c902a93ef8b383e94cebf1c816546ceca3da93b202aca49571275a602182b0dc6c

test:
  secret_key_base: b07505f04cd76c8fc12f14525c271edca521bb0aabd616c8d407ef737d3a6a43cdc3e412a186f6053746eab21818b3cbcfe67c40cbf5f6e97478dd2fc71ed21b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
